README.md, examples/update-operator.yaml
The current README references a non-existent file in `examples`, so I've pointed to the right file. I've also added clarification on how the agent runs and other minor things 😃
=> Add more detail on agent

pkg/operator/agent_manager.go
cc @dghubble, this is the proper fix for the problem we ran into on the installer.
Specifically, the first commit.
The other two are build improvements that are somewhat related, but not all that much.
=> operator/build: fix tagging consistency

build/bump-release, examples/update-operator.yaml.tmpl
Discussion: https://github.com/coreos/container-linux-update-operator/pull/71#pullrequestreview-36907630, https://github.com/coreos/container-linux-update-operator/pull/70#pullrequestreview-35125422
=> examples: Switch example deployment to use release tags

Jenkinsfile
This adds properties to do build discarding and trigger PR builds.
This roughly matches the existing manual property configuration.
The reason ghprb is used rather than any of the other options is that it
is the only option to do PR builds with sane user whitelisting for said
PRs.
cc @dghubble
=> Jenkinsfile: Set pipeline properties

pkg/agent/agent.go
Works around #75. Properly, it would also distinguish between
"retryable" and "unretryable" errors, but client-go doesn't give us
great granularity.
In the future, adding further granularity would be a good idea.
This also tweaks whether delete failures are fatal based on a discussion @aaronlevy and I had a while ago.
cc @dghubble 
Testing done: none yet 😦
=> pkg/agent: avoid exiting on watch termination

README.md, build/bump-release, examples/update-agent.yaml, examples/update-agent.yaml.tmpl, examples/update-operator.yaml, examples/update-operator.yaml.tmpl
Examples should show deploying the `update-operator` (coordinator) deployment and `update-agent` daemonset directly. The `manage-agent` feature is disabled according to plans outlined in #98
Note: Tectonic is still using the manage-agent feature so it hasn't been removed.
=> examples: Disable manage-agent feature in examples

examples/update-agent.yaml, examples/update-agent.yaml.tmpl
* Allow update-agent to run on nodes with a NodeSchedule taint, a common taint used for workload isolation
* Users deploying to clusters that use their own taints should adapt the tolerations in the examples according to their needs
=> examples: Add update-agent NoSchedule toleration

.gitignore, Makefile, build/build-release.sh, doc/development.md
* Add docs on development  loop, requirements, and how to validate basic functionality (#90)
* Makefile targets
* `build/build-image.sh` currently builds a binary, builds an image, and pushes the image behind `make image`. Add Makefile targets for each step individually to make development easier (open to different naming):
* `make release-bin` - Builds `update-operator` and `update-agent` inside the build image for repeatability
* `make image` - Builds the docker image
* `make docker-push` - Pushes the docker image (including to a developer's Quay account)
* Fixes #92 where scripts assumed sudo-less docker was allowed on the developer's machine
=> Add development docs and improve Makefile usability

pkg/operator/operator.go
When logging "(x of y) nodes are doing z", it is appropriate to log the action relating to the specific node, including its name. This aids users in understanding the operations and debugging problems.
For testing: `quay.io/dghubble/container-linux-update-operator:f1862d02100b5871188f9f6ce5f017634445bf3b`
Let's also be consistent about log lines starting with upper or lowercase and "%q" for strings.
Closes #72
=> pkg/operator: Show logs for individual node names

pkg/agent/agent.go, pkg/updateengine/client.go
Generating a status and putting it in our channel would deadlock if there was
already a ue status update waiting for us, which happens when a signal comes
along between the time we subscribe in New() and the time we actually start
consuming status updates. Instead, make the go routine do the first status
signal synthesis for us, and the problem goes away.
=> agent: moved getting first ue status to RecieveStatuses func

cmd/update-operator/main.go
I've updated the example manifests to always set `manage-agent` to false, per design discussions in #98 and #76.
Change `manage-agent` to default to false and show a warning when set to true since this is not the way we want to go going forward. Tectonic has a corresponding change to explicitly request the old behavior until a migration plan is ready. https://github.com/coreos/tectonic-installer/pull/1250
```
W0629 18:35:46.145820       1 main.go:43] use of -manage-agent=true is deprecated and will be removed in the future
I0629 18:35:46.148454       1 main.go:51] /bin/update-operator running
I0629 18:35:46.180891       1 leaderelection.go:179] attempting to acquire leader lease...
```
=> cmd/update-operator: Mark manage-agent deprecated

pkg/agent/agent.go
Current code uses `watchUpdateStatus(callback func, stop channel)` and `updateStatusCallback` to handle update_engine statuses appropriately. We no longer just wait for update_engine status to be UPDATE_STATUS_NEED_REBOOT and directly request a reboot (old code, unused).
=> pkg/agent: Remove unused waitForRebootSignal

cmd/update-agent/main.go, pkg/agent/agent.go
Pass in a top-level stop channel to the agent operator to use when it launches goroutines or calls `time.Sleep`. In theory, if we trapped on signals in cmd, we'd see every goroutine stop and a clean "Stopping agent" log line.
A general controller:
```
New(config Config) (*Kontroller)
func (k *Kontroller) Run(stop <-chan struct{}) {
// starting
wait.Until(processLoop, period, stop)
// stopping
}
func (k.Kontroller) process() {
// reconciliation logic
}
```
Similar to #108
=> Use controller pattern for update-agent

examples/update-agent.yaml, examples/update-agent.yaml.tmpl, examples/update-operator.yaml, examples/update-operator.yaml.tmpl
* Add update strategy so `kubectl apply` rolling updates if there is an existing daemonset
* By default, update-operator does not manage the update-agent daemonset so the custom label and annotation aren't needed.
=> examples: Add rolling update strategy and remove label/annotation

cmd/update-operator/main.go, pkg/constants/constants.go, pkg/k8sutil/selector.go, pkg/operator/agent_manager.go, pkg/operator/operator.go
*Note: Direct users of CLUO should use `-manage-agent=false` as shown in examples. Deploy the `update-agent` daemonset to select nodes in any way desired. CLUO is not opinionated.*
Background: When the update-operator is run with `manage-agent=true (dprecated)`, the operator creates update-agent as a daemonset across all nodes. We're migrating toward creating a daemonset which has a node selector so admins always have control. #76
When `-manage-agent=true`:
* Auto-label Container Linux nodes which lack the label `container-linux-update.v1.coreos.com/agent` with `container-linux-update.v1.coreos.com/agent=true`
* Don't auto-label nodes running non Container Linux distros
* Admins may set label `container-linux-update.v1.coreos.com/agent=false`
* Ignore nodes once the …
=> Auto-label Container Linux nodes with update-agent label

cmd/update-operator/main.go, pkg/agent/agent.go, pkg/constants/constants.go, pkg/k8sutil/metadata.go, pkg/k8sutil/selector.go, pkg/operator/agent_manager.go, pkg/operator/operator.go
This pr adds pre- and post-reboot actions.
With these changes, you will be able to configure actions which get run before a reboot is initiated and after one is completed, effectively gating it on either side. The actions taken are entirely arbitrary, and software that implements them only needs to be able to manipulate kubernetes annotations and read labels.
The changes to the `update-operator` ended up being a little more of an overhaul than I originally intended. With the addition of the new behavior, the `update-operator` has, broadly speaking, four state changes which it is responsible for. Those changes are
1. Find nodes where the post-reboot actions are completed successfully mark everything ready to go
2. Find nodes which have just rebooted and initiate post-reboot actions on them …
=> update-operator: Require before and after reboot annotations

pkg/operator/operator.go
When waiting for the before-reboot annotation, the operator outputs the incorrect annotation (`afterRebootAnnotations`). This fixes the log output to avoid confusion
=> operator: output correct beforeReboot annotation

pkg/agent/agent.go
By omitting a grace period, the object's default grace period will be used. This should allow pods with non-default termination grace periods to exit cleanly.
=> update-agent: Use default grace period for DeleteOptions when draining node

examples/update-operator.yaml
This updates the CLUO example manifest to tolerate running on master
nodes.
=> examples/operator: add tolerations to run on master

cmd/update-agent/main.go, pkg/agent/agent.go
This change makes the agent wait until all pods are terminated before rebooting. Prior to this change, the agent would reboot immediately after the pod delete request was made and, consequently, pods were not given the time needed to terminate gracefully.
=> update-agent: wait for pods to terminate before rebooting

examples/cluster-role.yaml
* Update the RBAC examples shortly before releasing v0.4.0
* #140 switches from endpoint-based leader election to configmap-based leader election
=> Change RBAC ClusterRole for CLUO v0.4.0

examples/cluster-role.yaml
When #137 was merged, it adds code to get each pod (rather than list) to determine whether it was successfully deleted. This requires an appropriate RBAC grant. Otherwise, having a grace period max is all that keeps it from stalling forever.
=> examples: Add RBAC permission to get individual pods

pkg/agent/agent.go
Borrowed from https://github.com/kubernetes/kubernetes/blob/v1.8.1/pkg/kubectl/cmd/drain.go#L565-L585
rel: #137 
Closes #149
=> pkg/agent: Consider NotFound or changed UID pods deleted

pkg/agent/agent.go
This adds a sync.WaitGroup to check all pods concurrently and avoid
erroneously extended grace periods.
=> agent: deserialize waitForPodDeletion check.

pkg/updateengine/client.go
On call errors, the `err` from the `Hello` was returned instead of the `call.Err` reason for the call failure.
=> pkg/updateengine: Return the right error on Call failures

pkg/drain/drain.go
* Check each pod's OwnerReferences to determine whether it is owned by an existing Daemonset. If so, exclude it from deletion as the pod would just be recreated by the Daemonset controller
* Drop usage of CreatedByAnnotation to deserialize the owner object of a pod when listing pods to delete during agent drains
Running `locksmithctl send-need-reboot` is not enough to reproduce the original issue. I  deployed a Typhoon 1.9.1 cluster with an intentionally old version of Container Linux. CLUO v0.4.1 reproduced the issue in which one node became unscheduable at a time, with no nodes able to actually upgrade.
Edited to test image and Container Linux upgrades were able to be applied.
* `quay.io/dghubble/container-linux-update-operator:77ac24a86c4e74d30e1a04bc6aa808371a1deb8e`
A proper release …
=> Fix pod deletion to be compatible with Kubernetes 1.9

doc/labels-and-annotations.md, pkg/agent/agent.go, pkg/constants/constants.go, pkg/k8sutil/metadata.go
agent: set a label when after successful os-update
This sets the label `container-linux-update.v1.coreos.com/os-update-staged: "true"` on nodes where the OS has been upgraded but not yet rebooted. This is so daemonsets like tectonic-torcx can run ASAP.
Fixes: #167
=>  agent: set a label when after successful os-update 

doc/labels-and-annotations.md, pkg/agent/agent.go, pkg/constants/constants.go, pkg/k8sutil/metadata.go, pkg/k8sutil/retry.go
This PR changes the agent to mark a node schedulable only if the agent was responsible for marking it unschedulable.
Prior to this change, the agent would always mark a node as schedulable when starting up. This could result in a node that had been marked unschedulable by an external process (eg. by an admin using kubectl) being marked schedulable by it's update agent if the agent restarted for some reason.
=> Only Mark Node Schedulable If Agent Marked Unschedulable 
